apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservices-demo.catalogName" . }}
  namespace: {{ include "microservices-demo.namespace" . }}
  labels:
    {{- include "microservices-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: catalog
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.catalogService.service.port }}
      targetPort: http
  selector:
    {{- include "microservices-demo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: catalog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservices-demo.catalogName" . }}
  namespace: {{ include "microservices-demo.namespace" . }}
  labels:
    {{- include "microservices-demo.labels" . | nindent 4 }}
    app.kubernetes.io/component: catalog
spec:
  replicas: {{ .Values.catalogService.replicaCount }}
  selector:
    matchLabels:
      {{- include "microservices-demo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: catalog
  template:
    metadata:
      labels:
        {{- include "microservices-demo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: catalog
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: catalog-service
          image: "{{ .Values.catalogService.image.repository }}:{{ .Values.catalogService.image.tag }}"
          imagePullPolicy: {{ .Values.catalogService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: AUTH_SERVICE_URL
              value: "http://{{ include "microservices-demo.authName" . }}:{{ .Values.authService.service.port }}"
            - name: AUTH_LOGIN_URL
              value: "{{ include "microservices-demo.publicBaseUrl" . }}/"
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 45
            periodSeconds: 20
          resources:
            {{- toYaml .Values.catalogService.resources | nindent 12 }}
