apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservices-demo.secretName" . }}
  namespace: {{ include "microservices-demo.namespace" . }}
  labels:
    {{- include "microservices-demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-username: {{ .Values.postgresql.username | quote }}
  postgres-password: {{ .Values.postgresql.password | quote }}
  jwt-secret: {{ .Values.authService.jwt.secret | quote }}
  demo-password: {{ .Values.authService.demoUser.password | quote }}
